language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - rbx
gemfile:
  - spec/gemfiles/capistrano-3.2
matrix:
  allow_failures:
    - rvm: rbx
  include:
    - rvm: 2.0.0
      gemfile: spec/gemfiles/capistrano-3.1
script: bundle exec rake spec
cache: bundler
